fn_args_layout = "Tall"
match_block_trailing_comma = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
max_width = 100
match_arm_blocks = true
merge_derives = true
wrap_comments = true
empty_item_single_line = true
remove_nested_parens = true
reorder_imports = true
tab_spaces = 4
trailing_comma = "Vertical"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
condense_wildcard_suffixes = true
group_imports = "Preserve"
imports_granularity = "Preserve"
imports_layout = "Mixed"
